// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpggicxvmgyljvoxlpnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZ2dpY3h2bWd5bGp2b3hscG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMDMxMjMsImV4cCI6MjA3NzU3OTEyM30.swv-8-C-45rFA2503gnnPE424LVrSwWVeO3QDsNHZQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});